In [1]:
from src.setup import * 
%load_ext rpy2.ipython 

In [3]:
%%R
install.packages("imager")

--- Please select a CRAN mirror for use in this session ---


* installing *source* package ‘bmp’ ...
** package ‘bmp’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (bmp)
* installing *source* package ‘tiff’ ...
** package ‘tiff’ successfully unpacked and MD5 sums checked
** using staged installation


checking for pkg-config... /usr/bin/pkg-config
checking for x86_64-conda-linux-gnu-gcc... /home/jose/anaconda3/envs/data-cleaning/bin/x86_64-conda-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether /home/jose/anaconda3/envs/data-cleaning/bin/x86_64-conda-linux-gnu-cc accepts -g... yes
checking for /home/jose/anaconda3/envs/data-cleaning/bin/x86_64-conda-linux-gnu-cc option to enable C11 features... none needed
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for unistd.h... (cached) yes
checking for TIFFCli

** libs


x86_64-conda-linux-gnu-cc -I"/home/jose/anaconda3/envs/data-cleaning/lib/R/include" -DNDEBUG -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jose/anaconda3/envs/data-cleaning/include   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jose/anaconda3/envs/data-cleaning/include -I/home/jose/anaconda3/envs/data-cleaning/include -Wl,-rpath-link,/home/jose/anaconda3/envs/data-cleaning/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jose/anaconda3/envs/data-cleaning/include -fdebug-prefix-map=/home/builder/r-4.2.0/miniconda/envs/r-4.2.0/conda-bld/r-base_1653520836469/work=/usr/local/src/conda/r-base-4.2.0 -fdebug-prefix-map=/home/jose/anaconda3/envs/data-cleaning=/usr/local/src/conda-prefix  -c read.c -o read.o
x86_64-conda-linux-gnu-cc -I"/home/jose/anaconda3/envs/data-cleaning/lib/R/include" -DNDEBUG -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jose/anaconda3/envs/data-cleaning/include   -DNDEB

installing to /home/jose/anaconda3/envs/data-cleaning/lib/R/library/00LOCK-tiff/00new/tiff/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (tiff)
* installing *source* package ‘cpp11’ ...
** package ‘cpp11’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of tempor

x86_64-conda-linux-gnu-cc -I"/home/jose/anaconda3/envs/data-cleaning/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jose/anaconda3/envs/data-cleaning/include -I/home/jose/anaconda3/envs/data-cleaning/include -Wl,-rpath-link,/home/jose/anaconda3/envs/data-cleaning/lib   `libpng-config --cflags` -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jose/anaconda3/envs/data-cleaning/include -fdebug-prefix-map=/home/builder/r-4.2.0/miniconda/envs/r-4.2.0/conda-bld/r-base_1653520836469/work=/usr/local/src/conda/r-base-4.2.0 -fdebug-prefix-map=/home/jose/anaconda3/envs/data-cleaning=/usr/local/src/conda-prefix  -c dummy.c -o dummy.o
x86_64-conda-linux-gnu-cc -I"/home/jose/anaconda3/envs/data-cleaning/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jose/anaconda3/envs/data-cleaning/include -I/home/jose/anaconda3/envs/data-cleaning/include -Wl,-rpath-link,/ho

installing to /home/jose/anaconda3/envs/data-cleaning/lib/R/library/00LOCK-png/00new/png/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (png)
* installing *source* package ‘jpeg’ ...
** package ‘jpeg’ successfully unpacked and MD5 sums checked
** using staged installation
** libs


x86_64-conda-linux-gnu-cc -I"/home/jose/anaconda3/envs/data-cleaning/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jose/anaconda3/envs/data-cleaning/include -I/home/jose/anaconda3/envs/data-cleaning/include -Wl,-rpath-link,/home/jose/anaconda3/envs/data-cleaning/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jose/anaconda3/envs/data-cleaning/include -fdebug-prefix-map=/home/builder/r-4.2.0/miniconda/envs/r-4.2.0/conda-bld/r-base_1653520836469/work=/usr/local/src/conda/r-base-4.2.0 -fdebug-prefix-map=/home/jose/anaconda3/envs/data-cleaning=/usr/local/src/conda-prefix  -c read.c -o read.o
x86_64-conda-linux-gnu-cc -I"/home/jose/anaconda3/envs/data-cleaning/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jose/anaconda3/envs/data-cleaning/include -I/home/jose/anaconda3/envs/data-cleaning/include -Wl,-rpath-link,/home/jose/anaconda3/envs/data

installing to /home/jose/anaconda3/envs/data-cleaning/lib/R/library/00LOCK-jpeg/00new/jpeg/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (jpeg)
* installing *source* package ‘downloader’ ...
** package ‘downloader’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installati

checking for x86_64-conda-linux-gnu-gcc... x86_64-conda-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether x86_64-conda-linux-gnu-cc accepts -g... yes
checking for x86_64-conda-linux-gnu-cc option to enable C11 features... none needed
checking whether the compiler supports GNU C++... yes
checking whether x86_64-conda-linux-gnu-c++ -std=gnu++11 accepts -g... yes
checking for x86_64-conda-linux-gnu-c++ -std=gnu++11 option to enable C++11 features... none needed
checking for x86_64-conda-linux-gnu-gfortran... x86_64-conda-linux-gnu-gfortran
checking whether the compiler supports GNU Fortran... yes
checking whether x86_64-conda-linux-gnu-gfortran accepts -g... yes
checking for expm1... yes
checking for fmin... yes
checking for finite.

** libs


x86_64-conda-linux-gnu-cc -I"/home/jose/anaconda3/envs/data-cleaning/lib/R/include" -DNDEBUG -DUSING_R -I. -Icore -Iinclude -Ivendor -I/home/jose/anaconda3/envs/data-cleaning/include/libxml2 -I/home/jose/anaconda3/envs/data-cleaning/include -DNDEBUG -DNTIMER -DNPRINT -DINTERNAL_ARPACK -DPRPACK_IGRAPH_SUPPORT -DIGRAPH_THREAD_LOCAL=/**/ -D_GNU_SOURCE=1 -I'/home/jose/anaconda3/envs/data-cleaning/lib/R/library/cpp11/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jose/anaconda3/envs/data-cleaning/include -I/home/jose/anaconda3/envs/data-cleaning/include -Wl,-rpath-link,/home/jose/anaconda3/envs/data-cleaning/lib  -fvisibility=hidden -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jose/anaconda3/envs/data-cleaning/include -fdebug-prefix-map=/home/builder/r-4.2.0/miniconda/envs/r-4.2.0/conda-bld/r-base_1653520836469/work=/usr/local/src/conda/r-base-4.2.0 -fdebug-prefix-map=/home/jose/anaconda3/

installing to /home/jose/anaconda3/envs/data-cleaning/lib/R/library/00LOCK-igraph/00new/igraph/libs
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (igraph)
* installing *source* package ‘imager’ ...
** package ‘imager’ successfully unpacked and MD5 sums checked
** using staged installation


checking for pkg-config... /usr/bin/pkg-config
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-conda-linux-gnu-c++ -std=gnu++14 accepts -g... yes
checking how to run the C++ preprocessor... x86_64-conda-linux-gnu-c++ -std=gnu++14 -E
checking for X... no
checking for XOpenDisplay in -lX11... no
X11 library not found, please install X11 library if you need the display capabilities of CImg.


configure: error: X11 not found but required, configure aborted.
ERROR: configuration failed for package ‘imager’
* removing ‘/home/jose/anaconda3/envs/data-cleaning/lib/R/library/imager’


also installing the dependencies ‘bmp’, ‘tiff’, ‘cpp11’, ‘png’, ‘jpeg’, ‘readbitmap’, ‘downloader’, ‘igraph’

trying URL 'https://mirror.las.iastate.edu/CRAN/src/contrib/bmp_0.3.tar.gz'
Content type 'application/x-gzip' length 111674 bytes (109 KB)
downloaded 109 KB

trying URL 'https://mirror.las.iastate.edu/CRAN/src/contrib/tiff_0.1-12.tar.gz'
Content type 'application/x-gzip' length 68272 bytes (66 KB)
downloaded 66 KB

trying URL 'https://mirror.las.iastate.edu/CRAN/src/contrib/cpp11_0.4.7.tar.gz'
Content type 'application/x-gzip' length 285779 bytes (279 KB)
downloaded 279 KB

trying URL 'https://mirror.las.iastate.edu/CRAN/src/contrib/png_0.1-8.tar.gz'
Content type 'application/x-gzip' length 24880 bytes (24 KB)
downloaded 24 KB

trying URL 'https://mirror.las.iastate.edu/CRAN/src/contrib/jpeg_0.1-10.tar.gz'
Content type 'application/x-gzip' length 18667 bytes (18 KB)
downloaded 18 KB

trying URL 'https://mirror.las.iastate.edu/CRAN/src/contrib/readbitmap_0.1.5.tar.gz'
Content ty

In [9]:
%%R
library(rvest)
library(tidyverse)

In [25]:
%%R
library(tidyverse)
library(rvest)

page <- read_html("https://en.wikipedia.org/wiki/2009_swine_flu_pandemic#")
table <- page %>%
    html_nodes("table") %>%
    .[[4]] %>%
    str_replace_all("<br>", " ") %>%
    minimal_html() %>%
    html_node("table") %>%
    html_table(fill = TRUE)
head(table, 3)

# A tibble: 3 × 9
  Name             Date   `World pop.` Subtype `Reproduction …` `Infected (est…`
  <chr>            <chr>  <chr>        <chr>   <chr>            <chr>           
1 Spanish flu[216] 1918–… 1.80 billion H1N1    1.80 (IQR, 1.47… 33% (500 millio…
2 Asian flu        1957–… 2.90 billion H2N2    1.65 (IQR, 1.53… >17% (>500 mill…
3 Hong Kong flu    1968–… 3.53 billion H3N2    1.80 (IQR, 1.56… >14% (>500 mill…
# … with 3 more variables: `Deaths worldwide` <chr>,
#   `Case fatality rate` <chr>, `Pandemic severity` <chr>


In addition: Warning message:
In stri_replace_all_regex(string, pattern, fix_replacement(replacement),  :
  argument is not an atomic vector; coercing


In [28]:
%%R 
library(tidyverse)
library(rvest)

page <- read_html("https://en.wikipedia.org/wiki/2009_swine_flu_pandemic#")
table <- page %>%
    html_nodes("table") %>%
    .[[4]] %>%
    str_replace_all('<br>', ' ') %>% 
    minimal_html() %>%
    html_node("table") %>% 
    html_table(fill = TRUE)
head(table, 3)

# A tibble: 3 × 9
  Name             Date   `World pop.` Subtype `Reproduction …` `Infected (est…`
  <chr>            <chr>  <chr>        <chr>   <chr>            <chr>           
1 Spanish flu[216] 1918–… 1.80 billion H1N1    1.80 (IQR, 1.47… 33% (500 millio…
2 Asian flu        1957–… 2.90 billion H2N2    1.65 (IQR, 1.53… >17% (>500 mill…
3 Hong Kong flu    1968–… 3.53 billion H3N2    1.80 (IQR, 1.56… >14% (>500 mill…
# … with 3 more variables: `Deaths worldwide` <chr>,
#   `Case fatality rate` <chr>, `Pandemic severity` <chr>


In addition: Warning message:
In stri_replace_all_regex(string, pattern, fix_replacement(replacement),  :
  argument is not an atomic vector; coercing


In [33]:
%%R
library(tidyverse)
library(rvest)

page <- read_html("https://en.wikipedia.org/wiki/2009_swine_flu_pandemic#")
table <- page %>% 
    html_nodes("table") %>%
    .[[4]] %>%
    str_replace_all('br', '') %>%
    minimal_html() %>% 
    html_node("table") %>% 
    html_table(fill = TRUE)
head(table, 7)

# A tibble: 7 × 9
  Name              Date  `World pop.` Subtype `Reproduction …` `Infected (est…`
  <chr>             <chr> <chr>        <chr>   <chr>            <chr>           
1 "Spanish flu[216… "191… "1.80 billi… "H1N1"  "1.80 (IQR, 1.4… "33% (500 milli…
2 "Asian flu"       "195… "2.90 billi… "H2N2"  "1.65 (IQR, 1.5… ">17% (>500 mil…
3 "Hong Kong flu"   "196… "3.53 billi… "H3N2"  "1.80 (IQR, 1.5… ">14% (>500 mil…
4 "1977 Russian fl… "197… "4.21 billi… "H1N1"  "?"              "?"             
5 "2009 swine flu … "200… "6.85 billi… "H1N1/… "1.46 (IQR, 1.3… "11–21% (0.7–1.…
6 "Typical seasona… "Eve… "7.75 billi… "A/H3N… "1.28 (IQR, 1.1… "5–15% (340 mil…
7 "Notes\n.mw-pars… "Not… "Notes\n.mw… "Notes… "Notes\n.mw-par… "Notes\n.mw-par…
# … with 3 more variables: `Deaths worldwide` <chr>,
#   `Case fatality rate` <chr>, `Pandemic severity` <chr>


In addition: Warning message:
In stri_replace_all_regex(string, pattern, fix_replacement(replacement),  :
  argument is not an atomic vector; coercing


In [35]:
%%R
library(tidyverse)
library(rvest)


data <- as_tibble(table, .name_repair = ~ c("Name", "Date", "Drop"))  %>%
    select(-drop) %>%
    slice(2:6) %>%
    mutate(Name = as.integer(gsub(",", "", Name)),
          Date = as.integer(as.factor(Date))
data

# Try to apply this method to a more tabular format 

RParsingError: Parsing status not OK - PARSING_STATUS.PARSE_ERROR

### Non - Tabular data

In [37]:
url_http = ("https://en.wikipedia.org/w/index.php?""title=List_of_HTTP_status_codes&oldid=947767948")

In [51]:
pprint(resp.content[43400:44000], width=55)

(b'class="vector-more-collapsible-item mw-list-item'
 b'"><a href="/w/index.php?title=List_of_HTTP_statu'
 b's_codes&amp;action=history"><span>View history</'
 b'span></a></li>\n\t\t</ul>\n\t\t\n\t</div>\n</div>'
 b'\n\n<div id="p-tb" class="vector-menu mw-portlet m'
 b'w-portlet-tb"  >\n\t<div class="vector-menu-headin'
 b'g">\n\t\tGeneral\n\t</div>\n\t<div class="vector-me'
 b'nu-content">\n\t\t\n\t\t<ul class="vector-menu-con'
 b'tent-list">\n\t\t\t\n\t\t\t<li id="t-whatlinkshe'
 b're" class="mw-list-item"><a href="/wiki/Special:'
 b'WhatLinksHere/List_of_HTTP_status_codes" title="'
 b'List of all English Wikipedia pages containing l'
 b'inks to this page [j]" accesskey="j"><span>What ')


In [38]:
import requests
resp = requests.get(url_http)
resp.status_code

200

In [39]:
from bs4 import BeautifulSoup 
soup = BeautifulSoup(resp.content)

In [40]:
codes = soup.find_all('dt')
for code in codes[:5] + codes[-5:]:
    print(code.text)

100 Continue
101 Switching Protocols
102 Processing (WebDAV; RFC 2518)
103 Early Hints (RFC 8297)
200 OK
524 A Timeout Occurred
525 SSL Handshake Failed
526 Invalid SSL Certificate
527 Railgun Error
530


In [41]:
def find_dds_after(node):
    dds = []
    sib = node.next_sibling 
    while True:

        if sib is None:
            break 

        elif not sib.name:
            sib = sib.next_sibling 

            continue 

        if sib.name == 'dd':
            dds.append(sib)
            sib = sib.next_sibling 

        else:
            break
    return dds

In [42]:
for code in codes[23:26]: 
    print(code.text)
    for dd in find_dds_after(code):
        print(" ", dd.text[:40], "...")

400 Bad Request
  The server cannot or will not process th ...
401 Unauthorized (RFC 7235)
  Similar to 403 Forbidden, but specifical ...
  Note: Some sites incorrectly issue HTTP  ...
402 Payment Required
  Reserved for future use. The original in ...


In [49]:
data = []
for code in codes:
    # All codes are 3 character numbers
    number = code.text[:3]
    # Parenthetical is not part of status
    text, note = code.text[4:], ""
    if " (" in text:
        text, note = text.split(" (")

        note = note.rstrip(")")

        # Compose description from list of strings
    description = "\n".join(t.text for t in find_dds_after(code))
    data.append([int(number), text, note, description])

In [50]:
# Creating a pandas dataframe to further work in the dataset 

(pd.DataFrame(data, columns=["Code", "Text", "Note", "Description"])
    .set_index('Code')
    .sort_index()
    .head(8))

Text              Note  \
Code                                          
100              Continue                     
101   Switching Protocols                     
102            Processing  WebDAV; RFC 2518   
103            Checkpoint                     
103           Early Hints          RFC 8297   
200                    OK                     
201               Created                     
202              Accepted                     

                                            Description  
Code                                                     
100   The server has received the request headers an...  
101   The requester has asked the server to switch p...  
102   A WebDAV request may contain many sub-requests...  
103   Used in the resumable requests proposal to res...  
103   Used to return some response headers before fi...  
200   Standard response for successful HTTP requests...  
201   The request has been fulfilled, resulting in t...  
202   The request has been accepted for processing, ...

### Binary Serialized Data Structures 

Concepts:

• Prefer existing libraries

• Bytes and struct data types

• Offset layout of data

In [62]:
arr = np.load(open('data/binary-3d.npy', 'rb'))
print(arr, '\n', arr.shape, arr.dtype)

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]] 
 (2, 2, 3) float64


In [82]:
%%bash 

hexdump -Cv data/binary-3d.npy

00000000  93 4e 55 4d 50 59 01 00  76 00 7b 27 64 65 73 63  |.NUMPY..v.{'desc|
00000010  72 27 3a 20 27 3c 66 38  27 2c 20 27 66 6f 72 74  |r': '<f8', 'fort|
00000020  72 61 6e 5f 6f 72 64 65  72 27 3a 20 46 61 6c 73  |ran_order': Fals|
00000030  65 2c 20 27 73 68 61 70  65 27 3a 20 28 32 2c 20  |e, 'shape': (2, |
00000040  32 2c 20 33 29 2c 20 7d  20 20 20 20 20 20 20 20  |2, 3), }        |
00000050  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
00000060  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
00000070  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 0a  |               .|
00000080  00 00 00 00 00 00 00 00  00 00 00 00 00 00 f0 3f  |...............?|
00000090  00 00 00 00 00 00 00 40  00 00 00 00 00 00 08 40  |.......@.......@|
000000a0  00 00 00 00 00 00 10 40  00 00 00 00 00 00 14 40  |.......@.......@|
000000b0  00 00 00 00 00 00 18 40  00 00 00 00 00 00 1c 40  |.......@.......@|
000000c0  00 00 00 00 00 00 20 40  00 00 00 00 00 00

In [83]:
%%bash 

file data/binary-3d.npy

data/binary-3d.npy: NumPy array, version 1.0, header length 118


In [91]:
# Parsing the file according to its specification 
import struct, ast
binfile = open("data/binary-3d.npy", 'rb')

# check that the magic header is correct 

if binfile.read(6) == b'\x93NUMPY':
    vermajor = ord(binfile.read(1))
    verminor = ord(binfile.read(1))
    print(f"Data appears to be NPY format, "
          f"version {vermajor}.{verminor}")
else:
    print("Data in unsupporting format")
    print(" ABORTING PROCESS ")

Data appears to be NPY format, version 1.0


In [92]:
header_len = struct.unpack('<H', binfile.read(2))[0]

header = binfile.read(header_len)

header_dict = ast.literal_eval(header.decode('utf-8'))
print(f"read {header_len} bytes"
      f"into dictionary: \n{header_dict} ")

read 118 bytesinto dictionary: 
{'descr': '<f8', 'fortran_order': False, 'shape': (2, 2, 3)} 


In [93]:
# Define spelling of data types and find the struct code
dtype_map = {'<i2': '<i', '<i4': '<l', '<i8': '<q',
'<f2': '<e', '<f4': '<f', '<f8': '<d'}

dtype = header_dict['descr']
fcode = dtype_map[dtype]

# Determine number of bytes from dtype spec

nbytes = int(dtype[2:])

# List to hold values
values = []

# Python 3.8+ "walrus operator"

while val_bytes := binfile.read(nbytes):
    values.append(struct.unpack(fcode, val_bytes)[0])
print("Values:", values)

Values: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0]


In [94]:
shape = header_dict['shape']
order = 'F' if header_dict['fortran_order'] else 'C'
newarr = np.array(values, dtype=dtype, order=order)
newarr = newarr.reshape(shape)
print(newarr, '\n', newarr.shape, newarr.dtype)
print("\nMatched standard parser:", (arr == newarr).all())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]] 
 (2, 2, 3) float64

Matched standard parser: True


## Custom Text Formats
Concepts:
• Line-oriented and hierarchical structures

• Heuristics to identify data of interest

• Character encodings and mojibake

• Guessing with chardet (character detection)

In [96]:
%%bash 

head -25 data/archive-zip.log

zipinfo output:
$ZIP = bless( {
  "versionNeededToExtract" => 0,
  "numberOfCentralDirectories" => 1,
  "centralDirectoryOffsetWRTStartingDiskNumber" => 360,
  "fileName" => "",
  "centralDirectorySize" => 76,
  "writeCentralDirectoryOffset" => 0,
  "diskNumber" => 0,
  "eocdOffset" => 0,
  "versionMadeBy" => 0,
  "diskNumberWithStartOfCentralDirectory" => 0,
  "desiredZip64Mode" => 0,
  "zip64" => 0,
  "zipfileComment" => "",
  "members" => [],
  "numberOfCentralDirectoriesOnThisDisk" => 1,
  "writeEOCDOffset" => 0
}, 'Archive::Zip::Archive' );

Found EOCD at 436 (0x1b4)

Found central directory for member #1 at 360
$CDMEMBER1 = bless( {
  "compressedSize" => 300,


In [105]:
def parse_cpan_log(fh):
    "Take a file-like object, produce a DF of classes generated"
    import pandas as pd 

    classes = {}
    in_class = False

    for n, line in enumerate(fh):
        # Remove surrouding whitespace
        line = line.strip()
        # Is this a new definition ?
        if line.startswith('$'):
            new_rec = {}
            in_class = True # One or more variables contains the 'state'
        # Is this the end of the defintion ? 
        elif line.endswith(');'):

            _, classname, _ = line.split()
            barename = classname.replace('Archive::Zip::', '')
            # Just removing extra quotes this way 
            name = ast.literal_eval(barename)
            # Distinguish entries with the same name by line number 
            classes[f"{name}_{n}"] = new_rec
            in_class = False

        # We are still finding new key/val pairs 
        elif in_class:
            # Split around Perl map operator 
            key, val = [s.strip() for s in line.split('=>')]
            # No trailing comma if it was present 
            val = val.rstrip(',')
            # Special null value needs to be translated
            val = "None" if val == "undef" else val
            # Also, just quote variables in vals 
            val = f'"{val}"' if val.startswith('$') else val 
            # Safe evaluate strings to Python objects
            key = ast.literal_eval(key)
            val = ast.literal_eval(val)
            # Add to record dictionary 
            new_rec[key] = val

    return pd.DataFrame(classes).T

In [107]:
df = parse_cpan_log(open('data/archive-zip.log'))
df.iloc[:, [4, 11, 26, 35]]

centralDirectorySize zip64       crc32 lastModFileDateTime
Archive_18                          76     0         NaN                 NaN
ZipFileMember_53                   NaN     0  2889301810          1345061049
ZipFileMember_86                   NaN     0  2889301810          1345061049
Archive_113                         72     1         NaN                 NaN
...                                ...   ...         ...                 ...
ZipFileMember_466                  NaN     0  3632233996          1325883762
Archive_493                         62     1         NaN                 NaN
ZipFileMember_528                  NaN     1  3632233996          1325883770
ZipFileMember_561                  NaN     1  3632233996          1325883770

[18 rows x 4 columns]

In [112]:
for fname in glob('data/character-encoding-*.txt'):
    bname = os.path.basename(fname)
    try:
        open(fname).read()
        print("Read successfully : ", bname, '\n')
    except Exception as err:
        print(err)

'utf-8' codec can't decode byte 0xcc in position 0: invalid continuation byte
'utf-8' codec can't decode byte 0xd7 in position 0: invalid continuation byte
'utf-8' codec can't decode byte 0xbd in position 0: invalid start byte
'utf-8' codec can't decode byte 0xc4 in position 171: invalid continuation byte


In [113]:
zh_file = 'data/character-encoding-zh.txt'
print(open(zh_file, encoding='GB18030').read())

字符编码（英語：Character encoding）、字集碼是把字符集中的字符编码为指
定集合中某一对象（例如：比特模式、自然数序列、8位元组或者电脉冲），以便文
本在计算机中存储和通过通信网络的传递。常见的例子包括将拉丁字母表编码成摩斯
电码和ASCII。
